# Generated by Django 4.0.4 on 2022-04-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_alter_todolist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
