# Generated by Django 4.0.4 on 2022-04-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_todolist_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='selected',
        ),
    ]
